apiVersion: telepresence.mr.telepresence/v1
kind: Session
metadata:
  labels:
    app.kubernetes.io/name: telepresencekubctrl
    app.kubernetes.io/managed-by: kustomize
  name: session-1
spec:
  sessionServices: []
  clientServices:
    - name: test
      maxClients: 2
      labels: {}
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
              - containerPort: 80
                name: hello
  clients:
    - id: client2
      connected: true
    - id: client3
      connected: true
    - id: client4
      connected: true
  timeoutSeconds: 10
  reutilizeTimeoutSeconds: 120
