---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.mr.telepresence
  resources:
  - sessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io/v1
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - watch
