apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    telepresence: "true"
    svc: "test2"
spec:
  containers:
    - name: nginx
      image: nginxdemos/nginx-hello
      ports:
        - containerPort: 8080
          name: hello
