apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    telepresence: "true"
    svc: "test1"
spec:
  containers:
    - name: nginx
      image: nginxdemos/nginx-hello
      ports:
        - containerPort: 8080
          name: hello
