---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.mr.telepresence
  resources:
  - sessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.mr.telepresence
  resources:
  - sessions/finalizers
  verbs:
  - update
- apiGroups:
  - core.mr.telepresence
  resources:
  - sessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gc.mr.telepresence
  resources:
  - gcregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
