# This rule is not used by the project session itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.mr.telepresence resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: session
    app.kubernetes.io/managed-by: kustomize
  name: session-viewer-role
rules:
- apiGroups:
  - core.mr.telepresence
  resources:
  - sessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.mr.telepresence
  resources:
  - sessions/status
  verbs:
  - get
