apiVersion: gc.mr.telepresence/v1alpha1
kind: GCRegistration
metadata:
  labels:
    app.kubernetes.io/name: gc
    app.kubernetes.io/managed-by: kustomize
  name: gcregistration-sample
spec:
  # TODO(user): Add fields here
