apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: session-manager-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: session-manager-sa
    namespace: default
roleRef:
  kind: Role
  name: session-manager-role
  apiGroup: rbac.authorization.k8s.io
