apiVersion: telepresence.mr.telepresence/v1
kind: Session
metadata:
  labels:
    app.kubernetes.io/name: telepresencekubctrl
    app.kubernetes.io/managed-by: kustomize
  name: session1
spec:
  sessionPods:
    - name: renderfusion
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
  backgroundPods:
    - name: renderfusion
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
  clients:
    - client1
  timeoutSeconds: 90
