apiVersion: telepresence.mr.telepresence/v1
kind: Session
metadata:
  labels:
    app.kubernetes.io/name: telepresencekubctrl
    app.kubernetes.io/managed-by: kustomize
  name: session1
spec:
  sessionServices:
    - name: asd
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
              - containerPort: 80
  timeoutSeconds: 120
  reutilizeTimeoutSeconds: 120
