# This rule is not used by the project telepresencekubctrl itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over telepresence.mr.telepresence.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: telepresencekubctrl
    app.kubernetes.io/managed-by: kustomize
  name: session-admin-role
rules:
- apiGroups:
  - telepresence.mr.telepresence
  resources:
  - sessions
  verbs:
  - '*'
- apiGroups:
  - telepresence.mr.telepresence
  resources:
  - sessions/status
  verbs:
  - get
