---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - deletecollection
- apiGroups:
  - telepresence.mr.telepresence
  resources:
  - sessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telepresence.mr.telepresence
  resources:
  - sessions/finalizers
  verbs:
  - update
- apiGroups:
  - telepresence.mr.telepresence
  resources:
  - sessions/status
  verbs:
  - get
  - patch
  - update
