apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: session-manager-role
  namespace: default
rules:
  - apiGroups: ["core.mr.telepresence"]
    resources: ["sessions"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
